default: &default
  adapter: mysql2
  charset: utfmb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  host: mariadb
  port: 3306
  username: root
  password:

development:
  <<: *default
  database: awkwardnarwhal_development

test:
  <<: *default
  database: awkwardnarwhal_test

production:
  <<: *default
  database: awkwardnarwhal_production
  username: awkwardnarwhal
  password: <%= ENV['AWKWARDNARWHAL_DATABASE_PASSWORD'] %>
